version: '3'

networks:
  local:

services:
  svelteapp:
    image: malurls_web

    build:
      context: ./SvelteApp
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - flask_api
    networks:
      - local
    
  flask_api:
    image: malurls_api
    context: .
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - local

