version: '3'

networks:
  local:

services:
  svelteapp:
    image: simonegramegna/malurls_web:latest

    build:
      context: ./SvelteApp
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - flask_api
    networks:
      - local
    
  flask_api:
    image: simonegramegna/malurls_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - local

  locust:
    image: simonegramegna/locust_api:latest
    build: 
      context: ./locust
      dockerfile: Dockerfile 
    ports:
      - "8089:8089"
    networks:
      - local

  prometheus:
    image: simonegramegna/prometheus_api:latest
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - local
        