version: '3'

networks:
  local:

services:

  flask_api:
    image: simonegramegna/malurls_api:latest
    container_name: malurls_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - local

  svelteapp:
    image: simonegramegna/malurls_svelteapp:latest
    container_name: malurls_svelteapp
    build:
      context: ./SvelteApp
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - flask_api
    networks:
      - local
    
  locust:
    image: simonegramegna/locust_api:latest
    container_name: locust_api
    build: 
      context: ./locust
      dockerfile: Dockerfile 
    ports:
      - "8089:8089"
    networks:
      - local

  prometheus:
    image: simonegramegna/prometheus_malurls:latest
    container_name: prometheus_malurls
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - local
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - "3000:3000"
    networks:
      - local
      