stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - data/urls_with_features.csv
    - src/data/make_dataset.py
    outs:
    - data/urls_with_features_selected.csv:
        cache: false
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/urls_with_features_selected.csv
    - src/features/build_features.py
    outs:
    - data/test.csv:
        cache: false
    - data/train.csv:
        cache: false
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/train.csv:
        cache: false
    - src/models/train_model.py
    outs:
    - models/model.pkl:
        cache: false
  predict_model:
    cmd: python src/models/predict_model.py
    deps:
    - data/test.csv:
        cache: false
    - src/models/predict_model.py
    outs:
    - reports/classification_report.json:
        cache: false
    - reports/confusion_matrix.json:
        cache: false
