stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
      - data/urls_with_features.csv
      - src/data/make_dataset.py
    #outs:
      #- data/urls_with_features_selected.csv:
          #cache: false
  build_features:
    cmd: python src/features/build_features.py
    deps:
      - data/urls_with_features_selected.csv
      - src/features/build_features.py
    outs:
      - data/test.csv:
          cache: false
      - data/train.csv:
          cache: false
  train_base_model:
    cmd:
      - python src/models/train_base_model.py
    deps:
      - src/models/utils.py
      - data/train.csv
      - src/models/train_base_model.py
    outs:
      - models/base_rf_model.pkl:
          cache: false

  train_tuned_model:
    cmd:
      - python src/models/train_tuned_model.py

    deps:
      - src/models/utils.py
      - data/train.csv
      - src/models/train_tuned_model.py

    outs:
      - models/tuned_rf_model.pkl:
          cache: false

  predict:
    cmd:
      - python src/models/predict.py
    deps:
      - src/models/utils.py
      - src/models/predict.py
      - models/base_rf_model.pkl
      - models/tuned_rf_model.pkl
      - data/test.csv
    outs:
      - reports/classification_report_base_rf.json:
          cache: false
      - reports/confusion_matrix_base_rf.json:
          cache: false
      - reports/classification_report_tuned_rf.json:
          cache: false
      - reports/confusion_matrix_tuned_rf.json:
          cache: false

