{
 "title": "MalURLs-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory stats allocation bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available CPU cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health checks failed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_health_checks_failed_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}