name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dvc
      run: pip install dvc

    - name: Install dvc s3
      run: pip install dvc-s3

    - name: Install codecarbon
      run: pip install codecarbon

    - name: Dagshub remote 1
      run: dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID_DAGSHUB }}

    - name: Dagshub remote 2
      run: dvc remote modify origin --local secret_access_key ${{ secrets.TOKEN_DAGSHUB }}

    - name: Pull data
      run: dvc pull -r origin

    - name: Install codecarbon
      run: pip install codecarbon

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Make dataset
      run: python3 src/data/make_dataset.py

    - name: Create features
      run: python3 src/features/build_features.py

    - name: Train base model
      run: python3 src/models/train_base_model.py

    - name: Train tuned model
      run: python3 src/models/train_tuned_model.py
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the docker image and push to docker hub
      run: |
        docker-compose build
        docker-compose push
