# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MalUrls-web-svelte

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2ad1b5fda8064107b8c1dd41da08f9f3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_973746d2c24a4359a818d3fa3d3a8b2e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2ad1b5fda8064107b8c1dd41da08f9f3 }}/simonegramegna/malurls_svelteapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MalUrls-web-svelte'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2456462ddcbb4c49bb0bfb4f3b71c400 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2ad1b5fda8064107b8c1dd41da08f9f3 }}/simonegramegna/malurls_svelteapp:${{ github.sha }}'