name: Performance monitoring - Alibidetect

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    outputs:
      id: result
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install dvc
      run: pip install dvc

    - name: Install dvc s3
      run: pip install dvc-s3

    - name: Dagshub remote 1
      run: dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID_DAGSHUB }}

    - name: Dagshub remote 2
      run: dvc remote modify origin --local secret_access_key ${{ secrets.TOKEN_DAGSHUB }}

    - name: Pull data
      run: dvc pull -r origin

    - name: Install requirements
      run: pip install -r performance_requirements.txt

    - name: Make dataset
      run: python3 src/data/make_dataset.py

    - name: Run outlier detection
      run: python performance_monitoring/outliers_detection.py

    - name: Print text file putput
      run: |
        $file_content=$(cat performance_monitoring/drift.txt)
        echo "$file_content"
        echo "::set-output name=drift-content::$file_content"


        
